coverage:
    status:
        project:
            default:
                target: auto
                threshold: 1%
        patch:
            default:
                target: auto
                threshold: 0%
                if_not_found: success
